{{- if .Values.admissionController.enabled }}
{{- if .Values.admissionController.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vertical-pod-autoscaler.admissionController.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vertical-pod-autoscaler.admissionController.labels" . | nindent 4 }}
  {{- with .Values.admissionController.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "vertical-pod-autoscaler.admissionController.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: /metrics
    {{- if .Values.admissionController.serviceMonitor.endpointConfig }}
      {{- toYaml .Values.admissionController.serviceMonitor.endpointConfig | nindent 6 }}
    {{- else }}
    {{- with .Values.admissionController.serviceMonitor.interval }}
      interval: {{ . }}
    {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
