apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fritzbox-exporter.fullname" . }}
  namespace: {{ template "fritzbox-exporter.namespace" $ }}
  labels:
    {{- include "fritzbox-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fritzbox-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fritzbox-exporter.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fritzbox-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 9042
              protocol: TCP
            - name: udp
              containerPort: 9042
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 30
          readinessProbe:
            tcpSocket:
              port: tcp
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command: ["fritzbox-exporter"]
          args: ["--gateway-url={{ .Values.config.fritzboxAddress }}:49000", "--gateway-luaurl={{ .Values.config.fritzboxAddress }}", "--username={{ .Values.config.username }}", "--password={{ .Values.config.password }}", "--metrics-file=/etc/fritzbox-exporter/metrics.json", "--lua-metrics-file=/etc/fritzbox-exporter/metrics-lua.json", "--listen-address={{ .Values.config.listenAddress }}"]
