{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fritzbox-exporter.fullname" . }}
  labels:
    {{- include "fritzbox-exporter.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  namespace: {{ template "fritzbox-exporter.namespace" $ }}
spec:
  jobLabel: {{ include "fritzbox-exporter.fullname" . }}
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      targetPort: {{ .Values.service.port }}
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ template "fritzbox-exporter.namespace" $ }}
  selector:
    matchLabels:
      {{- include "fritzbox-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
