{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fritzbox-exporter.serviceAccountName" . }}
  namespace: {{ template "fritzbox-exporter.namespace" $ }}
  labels:
    {{- include "fritzbox-exporter.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
