---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-unifi
  namespace: unifi
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
    - host: unifi.lan.unipig.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi-controller
                port:
                  number: 8443
