---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "unifi-controller.fullname" . }}
  namespace: {{ template "unifi-controller.namespace" $ }}
  labels:
    {{- include "unifi-controller.labels" . | nindent 4 }}
spec:
  ports:
    - name: '3478'
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: '10001'
      protocol: UDP
      port: 10001
      targetPort: 3478
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: '8443'
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: '8843'
      protocol: TCP
      port: 8843
      targetPort: 8843
    - name: '8880'
      protocol: TCP
      port: 8880
      targetPort: 8880
    - name: '6789'
      protocol: TCP
      port: 6789
      targetPort: 6789
  selector:
    {{- include "unifi-controller.selectorLabels" . | nindent 4 }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "unifi-controller.fullname" . }}-tcp
  namespace: {{ template "unifi-controller.namespace" $ }}
  {{- with .Values.tcpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: '8080'
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: '8443'
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: '8843'
      protocol: TCP
      port: 8843
      targetPort: 8843
    - name: '8880'
      protocol: TCP
      port: 8880
      targetPort: 8880
    - name: '6789'
      protocol: TCP
      port: 6789
      targetPort: 6789
  selector:
    {{- include "unifi-controller.selectorLabels" . | nindent 4 }}
  type: {{ .Values.tcpService.type }}
  {{- if .Values.tcpService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.tcpService.loadBalancerIP }}
  {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "unifi-controller.fullname" . }}-udp
  namespace: {{ template "unifi-controller.namespace" $ }}
  {{- with .Values.udpService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: '3478'
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: '10001'
      protocol: UDP
      port: 10001
      targetPort: 10001
  selector:
    {{- include "unifi-controller.selectorLabels" . | nindent 4 }}
  type: {{ .Values.udpService.type }}
  {{- if .Values.udpService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.udpService.loadBalancerIP }}
  {{- end }}
