{
 "title": "Alerts",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Critical Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{severity=\"critical\", alertstate=\"firing\", alertname!=\"Watchdog\"} or up==0)"
    }
   ]
  },
  {
   "title": "Alerts over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", alertname!=\"Watchdog\"}) by (severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ALERTS{severity=\"warning\", alertstate=\"firing\", alertname!=\"Watchdog\"} or up==0)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname!=\"Watchdog\"}"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"pending\", alertname!=\"Watchdog\"}"
    }
   ]
  }
 ]
}