{
 "title": "Velero Backup",
 "description": "Stats for Velero backups",
 "tags": [
  "velero",
  "backup"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total,schedule)"
    }
   },
   {
    "name": "csi_backup_name",
    "label": "CSI Backup Name",
    "query": {
     "query": "label_values(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\"},backupName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Success Total",
   "type": "stat",
   "description": "The sum of one-off backup and schedule backup success total ",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "velero_backup_total" }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "gauge",
   "description": "The Success Rate is lower when a Backup is running.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Backup Deletion Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_deletion_success_total{schedule=~\"$schedule\"}) / sum(velero_backup_deletion_attempt_total{schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Volume Snapshot Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{schedule=~\"$schedule\"}) / sum(velero_volume_snapshot_attempt_total{schedule=~\"$schedule\"})\n"
    }
   ]
  },
  {
   "title": "Hours since last Backup",
   "type": "table",
   "description": "for schedule backup use only",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(time() - velero_backup_last_successful_timestamp{schedule!=\"\"}) / 60 / 60",
     "legendFormat": "{{schedule}}"
    }
   ]
  },
  {
   "title": "Total Backup Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(velero_backup_total)", "legendFormat": "Backup Total" },
    {
     "expr": "velero_backup_active_total{schedule=~\"$schedule\"}\r\n#missing metric (https://github.com/vmware-tanzu/velero/issues/2254)",
     "legendFormat": "Backup {{schedule}}"
    }
   ]
  },
  {
   "title": "Backups per Hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_success_total{schedule=~\"$schedule\"}[1h])) > 0",
     "legendFormat": "Backup success"
    },
    {
     "expr": "sum(increase(velero_backup_failure_total{schedule=~\"$schedule\"}[1h])) > 0",
     "legendFormat": "Backup failure"
    },
    {
     "expr": "sum(increase(velero_backup_partial_failure_total{schedule=~\"$schedule\"}[1h])) > 0",
     "legendFormat": "Backup partial failure"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_success_total{schedule=~\"$schedule\"}[1h])) > 0",
     "legendFormat": "Backup deletion success"
    },
    {
     "expr": "sum(increase(velero_backup_deletion_failure_total{schedule=~\"$schedule\"}[1h])) > 0",
     "legendFormat": "Backup deletion failure"
    }
   ]
  },
  {
   "title": "Backup Time Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(velero_backup_duration_seconds_bucket{schedule=~\"$schedule\",le!=\"+Inf\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Backup Size per Schedule",
   "type": "timeseries",
   "description": "If your Storage component creates the Volume-Snapshots and not Velero, for example with Longhorn, then this will not displayed in the panel.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (schedule) (avg_over_time(velero_backup_tarball_size_bytes{schedule=~\"$schedule\"}[15m]))",
     "legendFormat": "{{schedule}}"
    },
    {
     "expr": "avg_over_time(velero_backup_tarball_size_bytes{schedule!~\".+\"}[15m])",
     "legendFormat": "Non Scheduled"
    }
   ]
  },
  {
   "title": "Restore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Restore Success Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "velero_restore_total" }
     ]
    },
    {
     "title": "Restore Success Rate",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(velero_restore_success_total{schedule=~\"$schedule\"}) / sum(velero_restore_attempt_total{schedule=~\"$schedule\"})"
      }
     ]
    },
    {
     "title": "Restore per hour",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(increase(velero_restore_success_total{schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "Restore success"
      },
      {
       "expr": "round(sum(increase(velero_restore_failed_total{schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "Restore failure"
      },
      {
       "expr": "round(sum(increase(velero_restore_validation_failed_total{schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "Restore validation failure"
      },
      {
       "expr": "round(sum(increase(velero_restore_partial_failure_total{schedule=~\"$schedule\"}[1h])))",
       "legendFormat": "Restore partial failure"
      }
     ]
    },
    {
     "title": "Total Restore Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(velero_restore_total)", "legendFormat": "Restore Total" }
     ]
    }
   ]
  },
  {
   "title": "CSI",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "CSI per Hour",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "round(sum(increase(velero_csi_snapshot_attempt_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
       "legendFormat": "CSI Snapshot attempt"
      },
      {
       "expr": "round(sum(increase(velero_csi_snapshot_success_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
       "legendFormat": "CSI Snapshot success"
      },
      {
       "expr": "round(sum(increase(velero_csi_snapshot_failure_total{schedule=~\"$schedule\", backupName=~\"$csi_backup_name\"}[1h])))",
       "legendFormat": "CSI Snapshot failure"
      }
     ]
    }
   ]
  }
 ]
}