apiVersion: v2
name: unifi-controller
description: A Helm Chart for the UniFi WiFi Controller
type: application
<<<<<<< HEAD
version: "0.1.3"
appVersion: "v0.1.3"
=======
version: "0.1.2"
appVersion: "v0.1.2"
>>>>>>> 76fbca8 (updated unifi controller chart)
