apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  namespace: {{ template "unifi-poller.namespace" $ }}
  labels:
    {{- include "unifi-poller.labels" . | nindent 4 }}
stringData:
  unifi-poller.conf: |
      [poller]
        debug = {{ .Values.config.poller.debug }}
        quiet = false
        plugins = []
      [prometheus]
        disable = {{ .Values.config.prometheus.disable }}
        http_listen = "{{ .Values.config.prometheus.http_listen }}"
        report_errors = {{ .Values.config.prometheus.report_errors }}
      [unifi]
        dynamic = {{ .Values.config.unifi.dynamic }}
      [[unifi.controller]]
        url = "{{ .Values.config.unificontroller.url }}"
        user = "{{ .Values.config.unificontroller.user }}"
        pass = "{{ .Values.config.unificontroller.pass }}"
        sites = ["{{ .Values.config.unificontroller.sites }}"]
        save_ids = {{ .Values.config.unificontroller.save_ids }}
        save_dpi = {{ .Values.config.unificontroller.save_dpi }}
        save_sites = {{ .Values.config.unificontroller.save_sites }}
        verify_ssl = {{ .Values.config.unificontroller.verify_ssl }}
