apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  namespace: {{ template "unifi-poller.namespace" $ }}
  labels:
    {{- include "unifi-poller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "{{ .Values.service.port }}"
      port: {{ .Values.service.port }}
      targetPort: 9130
      protocol: TCP
  selector:
    {{- include "unifi-poller.labels" . | nindent 4 }}
