{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unifi-poller.fullname" . }}
  labels:
    app: {{ template "unifi-poller.name" . }}
    chart: {{ template "unifi-poller.chart" . }}
    heritage: {{ .Release.Service }}
  {{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
  namespace: {{ template "unifi-poller.namespace" $ }}
spec:
  jobLabel: {{ include "unifi-poller.fullname" . }}
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
      port: "{{ .Values.service.port }}"
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ template "unifi-poller.namespace" $ }}
  selector:
    matchLabels:
      {{- include "unifi-poller.selectorLabels" . | nindent 6 }}
{{- end }}
