{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "unifi-poller.serviceAccountName" . }}
  namespace: {{ template "unifi-poller.namespace" $ }}
  labels:
    {{- include "unifi-poller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
