{
 "title": "Alerts",
 "tags": [
  "alertmanager",
  "k8s"
 ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Critical Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity=\"critical\", alertstate=\"firing\", alertname!=\"Watchdog\"} or up==0)"
    }
   ]
  },
  {
   "title": "Alerts over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", alertname!=\"Watchdog\"}) by (severity)",
     "legendFormat": "{{ severity }}"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity=\"warning\", alertstate=\"firing\", alertname!=\"Watchdog\"} or up==0)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", alertname!=\"Watchdog\"}"
    }
   ]
  },
  {
   "title": "Pending Alerts",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"pending\", alertname!=\"Watchdog\"}"
    }
   ]
  }
 ]
}